name: Manual Build

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Lambda Layer
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14.x

    - name: Install Packages
      run: npm install

    - name: Create Lambda Layer
      run: make chrome_aws_lambda.zip

    - name: Upload Layer Artifact
      uses: actions/upload-artifact@v2
      with:
        name: chrome_aws_lambda
        path: chrome_aws_lambda.zip
